- name: Revoke SSH access
  authorized_key:
     user: "{{ user_name1 }}"
     state: absent
     key: "{{ lookup('file', '../../../sshkeys/{{ user_name1 }}/id_rsa.pub') }}"
  tags:
    - revoke
    
 - name: Remove user
   user:
     name: "{{ user_name1 }}"
     state: absent
     remove: yes
   tags:
    - remove